import { MigrationInterface, QueryRunner } from "typeorm";

export class AllEnityAddedUserId1772892978314 implements MigrationInterface {
    name = 'AllEnityAddedUserId1772892978314'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "subscription_plans" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "tenant_traffic" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "page_traffic" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "platform_settings" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "subscribers" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "site_settings" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "brands" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "pages" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "faqs" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "product_attributes" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "products" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "promotions" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "supplier_payments" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "files" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" ADD CONSTRAINT "FK_f06b516e6bdc44a370ca7d69a0e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_0e2bb90ad27fa92910185792aca" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_traffic" ADD CONSTRAINT "FK_718255c609f0cf64754afc09b66" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page_traffic" ADD CONSTRAINT "FK_b2457320224276606ebc0023a52" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "platform_settings" ADD CONSTRAINT "FK_637c1fee01f70e1a7eb00261ac8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscribers" ADD CONSTRAINT "FK_0c99e87bda40ab7c44e49e88ef8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "site_settings" ADD CONSTRAINT "FK_e3c0b0f92d46ec87d2aedb08955" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brands" ADD CONSTRAINT "FK_5d26f3a7d19d380538c9dd57d06" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_2296b7fe012d95646fa41921c8b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages" ADD CONSTRAINT "FK_98ceb5433a66707b9c649503dce" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "faqs" ADD CONSTRAINT "FK_efa33cfbfffe5e5ddf10b8360ef" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_b3aba33228acd59f2d734c31b82" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attributes" ADD CONSTRAINT "FK_2cf0031fe3f0a6a5e9085f390fe" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_e96e3e3799fe4b21ad07b3b3cff" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_176b502c5ebd6e72cafbd9d6f70" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotions" ADD CONSTRAINT "FK_6b9285677a2fa46c96d6f88e9fd" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_bf96e1bdbc1ce2ec1f7fe66e8c2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_33d621ab2004ace0d32a966e250" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_c13036093717212c2c6aa111c73" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_payments" ADD CONSTRAINT "FK_99283b63c5ce97cf7a4dcc08808" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_a7435dbb7583938d5e7d1376041" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_26daf5e433d6fb88ee32ce93637" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_e51672a4898b02f686769f71c2a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_49a0ca239d34e74fdc4e0625a78" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_0cec49f8f07d5ac4a8a9bbe6ac2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD CONSTRAINT "FK_9974c02e617aa96ddafd8404323" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_b7213c20c1ecdc6597abc8f1212" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_b7213c20c1ecdc6597abc8f1212"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP CONSTRAINT "FK_9974c02e617aa96ddafd8404323"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_0cec49f8f07d5ac4a8a9bbe6ac2"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_49a0ca239d34e74fdc4e0625a78"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_e51672a4898b02f686769f71c2a"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_26daf5e433d6fb88ee32ce93637"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_a7435dbb7583938d5e7d1376041"`);
        await queryRunner.query(`ALTER TABLE "supplier_payments" DROP CONSTRAINT "FK_99283b63c5ce97cf7a4dcc08808"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_c13036093717212c2c6aa111c73"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_33d621ab2004ace0d32a966e250"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_bf96e1bdbc1ce2ec1f7fe66e8c2"`);
        await queryRunner.query(`ALTER TABLE "promotions" DROP CONSTRAINT "FK_6b9285677a2fa46c96d6f88e9fd"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_176b502c5ebd6e72cafbd9d6f70"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_e96e3e3799fe4b21ad07b3b3cff"`);
        await queryRunner.query(`ALTER TABLE "product_attributes" DROP CONSTRAINT "FK_2cf0031fe3f0a6a5e9085f390fe"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_b3aba33228acd59f2d734c31b82"`);
        await queryRunner.query(`ALTER TABLE "faqs" DROP CONSTRAINT "FK_efa33cfbfffe5e5ddf10b8360ef"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP CONSTRAINT "FK_98ceb5433a66707b9c649503dce"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_2296b7fe012d95646fa41921c8b"`);
        await queryRunner.query(`ALTER TABLE "brands" DROP CONSTRAINT "FK_5d26f3a7d19d380538c9dd57d06"`);
        await queryRunner.query(`ALTER TABLE "site_settings" DROP CONSTRAINT "FK_e3c0b0f92d46ec87d2aedb08955"`);
        await queryRunner.query(`ALTER TABLE "subscribers" DROP CONSTRAINT "FK_0c99e87bda40ab7c44e49e88ef8"`);
        await queryRunner.query(`ALTER TABLE "platform_settings" DROP CONSTRAINT "FK_637c1fee01f70e1a7eb00261ac8"`);
        await queryRunner.query(`ALTER TABLE "page_traffic" DROP CONSTRAINT "FK_b2457320224276606ebc0023a52"`);
        await queryRunner.query(`ALTER TABLE "tenant_traffic" DROP CONSTRAINT "FK_718255c609f0cf64754afc09b66"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_0e2bb90ad27fa92910185792aca"`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" DROP CONSTRAINT "FK_f06b516e6bdc44a370ca7d69a0e"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "files" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "supplier_payments" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "promotions" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "product_attributes" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "faqs" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "brands" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "site_settings" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "subscribers" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "platform_settings" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "page_traffic" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "tenant_traffic" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "subscription_plans" DROP COLUMN "user_id"`);
    }

}
