'use client';

import { useEffect, useState, useCallback } from 'react';
import toast from 'react-hot-toast';
import { fetchAPI } from '@/services/api';
import { useSettings } from '@/hooks/SettingsContext';
import { generateCode } from '../utils/priceBookHelpers';

export function usePriceBookDashboard() {
    const { settings } = useSettings();
    const globalCurrency = settings?.currency || 'BDT';

    const [priceBooks, setPriceBooks] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingBook, setEditingBook] = useState<any>(null);
    const [searchQuery, setSearchQuery] = useState('');
    const [codeAutoGenerated, setCodeAutoGenerated] = useState(true);

    const [confirmModal, setConfirmModal] = useState({
        isOpen: false,
        title: '',
        message: '',
        onConfirm: () => {},
    });

    const [formData, setFormData] = useState({
        name: '',
        code: '',
        type: 'RETAIL',
        currency: 'BDT',
        isActive: true,
        validFrom: '',
        validTo: ''
    });

    const loadPriceBooks = useCallback(async () => {
        try {
            setLoading(true);
            const res = await fetchAPI('/pricing/price-books');
            if (res.success) {
                setPriceBooks(res.data || []);
            }
        } catch (error) {
            console.error('Failed to load price books', error);
            toast.error('Failed to load Price Books');
        } finally {
            setLoading(false);
        }
    }, []);

    useEffect(() => {
        void loadPriceBooks();
    }, [loadPriceBooks]);

    useEffect(() => {
        if (globalCurrency) {
            setFormData(prev => ({ ...prev, currency: globalCurrency }));
        }
    }, [globalCurrency]);

    const resetForm = useCallback(() => {
        setFormData({
            name: '',
            code: '',
            type: 'RETAIL',
            currency: globalCurrency,
            isActive: true,
            validFrom: '',
            validTo: ''
        });
        setCodeAutoGenerated(true);
        setEditingBook(null);
    }, [globalCurrency]);

    const openCreateModal = () => {
        resetForm();
        setIsModalOpen(true);
    };

    const openEditModal = (book: any) => {
        setEditingBook(book);
        setCodeAutoGenerated(false);
        setFormData({
            name: book.name,
            code: book.code,
            type: book.type,
            currency: book.currency || globalCurrency,
            isActive: book.isActive,
            validFrom: book.validFrom ? new Date(book.validFrom).toISOString().slice(0, 16) : '',
            validTo: book.validTo ? new Date(book.validTo).toISOString().slice(0, 16) : ''
        });
        setIsModalOpen(true);
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        if (formData.type === 'PROMOTIONAL') {
            if (!formData.validFrom || !formData.validTo) {
                toast.error('Promotional price books require both Valid From and Valid To dates.');
                return;
            }
            const fromDate = new Date(formData.validFrom);
            const toDate = new Date(formData.validTo);
            if (toDate <= fromDate) {
                toast.error('Valid To date must be chronologically after the Valid From date.');
                return;
            }
        }

        try {
            const url = editingBook ? `/pricing/price-books/${editingBook.id}` : '/pricing/price-books';
            const method = editingBook ? 'PATCH' : 'POST';

            const payload = {
                ...formData,
                validFrom: formData.validFrom ? new Date(formData.validFrom).toISOString() : null,
                validTo: formData.validTo ? new Date(formData.validTo).toISOString() : null
            };

            const res = await fetchAPI(url, {
                method,
                body: JSON.stringify(payload)
            });

            if (res.success) {
                toast.success(`Price Book ${editingBook ? 'updated' : 'created'} successfully`);
                setIsModalOpen(false);
                resetForm();
                void loadPriceBooks();
            }
        } catch (error: any) {
            console.error('Error saving price book', error);
            toast.error(error.message || 'Error saving Price Book');
        }
    };

    const handleDelete = (id: string) => {
        setConfirmModal({
            isOpen: true,
            title: 'Delete Price Book',
            message: 'Are you sure you want to delete this price book? This action cannot be undone and any assigned custom pricing tiers will be permanently removed.',
            onConfirm: async () => {
                try {
                    const res = await fetchAPI(`/pricing/price-books/${id}`, { method: 'DELETE' });
                    if (res.success) {
                        toast.success('Price Book deleted successfully');
                        setPriceBooks(prev => prev.filter(b => b.id !== id));
                    }
                } catch (error) {
                    console.error('Error deleting price book', error);
                    toast.error('Error deleting Price Book');
                }
            }
        });
    };

    return {
        priceBooks,
        loading,
        isModalOpen,
        setIsModalOpen,
        editingBook,
        searchQuery,
        setSearchQuery,
        codeAutoGenerated,
        setCodeAutoGenerated,
        confirmModal,
        setConfirmModal,
        formData,
        setFormData,
        openCreateModal,
        openEditModal,
        handleSubmit,
        handleDelete,
        globalCurrency,
        settings,
    };
}
