version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: eCommerce-multi-tenant-saasmongodb-dev
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - eCommerce-multi-tenant-saasnetwork-dev

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    # restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_ADMIN_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_ADMIN_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - eCommerce-multi-tenant-saasnetwork-dev

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: eCommerce-multi-tenant-saasapp-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV={NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - SEED_DB=${SEED_DB}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - STORE_ID=${STORE_ID}
      - STORE_PASSWORD=${STORE_PASSWORD}
      - IS_LIVE=${IS_LIVE}
    depends_on:
      - mongodb
    networks:
      - eCommerce-multi-tenant-saasnetwork-dev
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./lib:/app/lib
      - ./models:/app/models
      - ./contexts:/app/contexts
      - ./scripts:/app/scripts
      - ./public:/app/public
      - ./styles:/app/styles
      - /app/node_modules
      - /app/.next

networks:
  eCommerce-multi-tenant-saasnetwork-dev:
    driver: bridge

volumes:
  mongodb_dev_data:
    driver: local
