services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres-db-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: multi_tenant_ecommerce
      TZ: "GMT"
      PGTZ: "GMT"
    ports:
      - "5434:5432"
    networks:
      - main_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_ecommerce
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=gowtampaul0@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=gowtampaul1995@
    ports:
      - "5051:80"
    depends_on:
      - postgres
    networks:
      - main_network

  redis:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data # Optional: Persist Redis data
    networks:
      - main_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander-dev
    environment:
      - REDIS_HOST=redis-dev
      - REDIS_PORT=6379
    ports:
      - "8088:8081"
    depends_on:
      - redis
    networks:
      - main_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server-dev
    ports:
      - "3900:3900"
    env_file:
      - ./server/.env.development
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - main_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client-dev
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.local
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
  postgres_data:
  redis-data:
