'use client';

import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
    Scale, 
    Plus, 
    Trash2, 
    Edit2, 
    Loader2, 
    BadgeDollarSign, 
    Check, 
    ShieldAlert, 
    Clock,
    Info
} from 'lucide-react';
import { fetchAPI } from '@/services/api';
import toast from 'react-hot-toast';
import ConfirmModal from '@/components/shared/ConfirmModal';
import { useSettings } from '@/hooks/SettingsContext';

/** Converts a name string to an UPPER-KEBAB code. e.g. "Eid Campaign 2026" → "EID-CAMPAIGN-2026" */
function generateCode(name: string): string {
    return name
        .trim()
        .toUpperCase()
        .replace(/[^A-Z0-9\s]/g, '')   // strip special chars
        .replace(/\s+/g, '-')           // spaces → dash
        .replace(/-+/g, '-')            // collapse multiple dashes
        .replace(/^-|-$/g, '');         // trim leading/trailing dashes
}

export default function PriceBooks() {
    const { settings } = useSettings();
    const globalCurrency = settings?.currency || 'BDT';

    const [priceBooks, setPriceBooks] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [editingBook, setEditingBook] = useState<any>(null);
    const [searchQuery, setSearchQuery] = useState('');
    const [codeAutoGenerated, setCodeAutoGenerated] = useState(true); // tracks if code is still auto-derived

    const [confirmModal, setConfirmModal] = useState({
        isOpen: false,
        title: '',
        message: '',
        onConfirm: () => {},
    });

    const [formData, setFormData] = useState({
        name: '',
        code: '',
        type: 'RETAIL',
        currency: 'BDT',
        isActive: true,
        validFrom: '',
        validTo: ''
    });

    useEffect(() => {
        loadPriceBooks();
    }, []);

    useEffect(() => {
        if (globalCurrency) {
            setFormData(prev => ({ ...prev, currency: globalCurrency }));
        }
    }, [globalCurrency]);

    const loadPriceBooks = async () => {
        try {
            setLoading(true);
            const res = await fetchAPI('/pricing/price-books');
            if (res.success) {
                setPriceBooks(res.data || []);
            }
        } catch (error) {
            console.error('Failed to load price books', error);
            toast.error('Failed to load Price Books');
        } finally {
            setLoading(false);
        }
    };

    const getTypeHelperText = () => {
        switch (formData.type) {
            case 'RETAIL':
                return {
                    text: 'Base storefront catalog. Provides default prices for guest and standard retail shoppers. Only one active Retail price book is allowed per currency.',
                    color: 'text-brand-700 dark:text-brand-300 bg-brand-50/50 dark:bg-brand-950/20 border-brand-200 dark:border-brand-800'
                };
            case 'PROMOTIONAL':
                return {
                    text: 'Active campaign catalog. Promotional price books automatically override Retail catalogs during their scheduled active window. Start and End dates are required.',
                    color: 'text-rose-700 dark:text-rose-300 bg-rose-50/50 dark:bg-rose-950/20 border-rose-200 dark:border-rose-800'
                };
            case 'WHOLESALE':
                return {
                    text: 'Bulk/B2B price catalog. Excluded from normal storefront fallbacks. Applies only when checked out with the wholesale channel or via wholesale customer accounts.',
                    color: 'text-amber-700 dark:text-amber-300 bg-amber-50/50 dark:bg-amber-950/20 border-amber-200 dark:border-amber-800'
                };
            case 'CUSTOMER_SPECIFIC':
                return {
                    text: 'VIP/Contract catalog. Excluded from normal storefront fallbacks. Applies only to specific orders where this code is explicitly passed.',
                    color: 'text-indigo-700 dark:text-indigo-300 bg-indigo-50/50 dark:bg-indigo-950/20 border-indigo-200 dark:border-indigo-800'
                };
            default:
                return null;
        }
    };

    const resetForm = () => {
        setFormData({
            name: '',
            code: '',
            type: 'RETAIL',
            currency: globalCurrency,
            isActive: true,
            validFrom: '',
            validTo: ''
        });
        setCodeAutoGenerated(true);
        setEditingBook(null);
    };

    const openCreateModal = () => {
        resetForm();
        setIsModalOpen(true);
    };

    const openEditModal = (book: any) => {
        setEditingBook(book);
        setCodeAutoGenerated(false); // editing an existing book → code is fixed
        setFormData({
            name: book.name,
            code: book.code,
            type: book.type,
            currency: book.currency || globalCurrency,
            isActive: book.isActive,
            validFrom: book.validFrom ? new Date(book.validFrom).toISOString().slice(0, 16) : '',
            validTo: book.validTo ? new Date(book.validTo).toISOString().slice(0, 16) : ''
        });
        setIsModalOpen(true);
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        // Client-side validations
        if (formData.type === 'PROMOTIONAL') {
            if (!formData.validFrom || !formData.validTo) {
                toast.error('Promotional price books require both Valid From and Valid To dates.');
                return;
            }
            const fromDate = new Date(formData.validFrom);
            const toDate = new Date(formData.validTo);
            if (toDate <= fromDate) {
                toast.error('Valid To date must be chronologically after the Valid From date.');
                return;
            }
        }

        try {
            const url = editingBook ? `/pricing/price-books/${editingBook.id}` : '/pricing/price-books';
            const method = editingBook ? 'PATCH' : 'POST';

            // Clean up payload dates
            const payload = {
                ...formData,
                validFrom: formData.validFrom ? new Date(formData.validFrom).toISOString() : null,
                validTo: formData.validTo ? new Date(formData.validTo).toISOString() : null
            };

            const res = await fetchAPI(url, {
                method,
                body: JSON.stringify(payload)
            });

            if (res.success) {
                toast.success(`Price Book ${editingBook ? 'updated' : 'created'} successfully`);
                setIsModalOpen(false);
                resetForm();
                loadPriceBooks();
            }
        } catch (error: any) {
            console.error('Error saving price book', error);
            toast.error(error.message || 'Error saving Price Book');
        }
    };

    const handleDelete = (id: string) => {
        setConfirmModal({
            isOpen: true,
            title: 'Delete Price Book',
            message: 'Are you sure you want to delete this price book? This action cannot be undone and any assigned custom pricing tiers will be permanently removed.',
            onConfirm: async () => {
                try {
                    const res = await fetchAPI(`/pricing/price-books/${id}`, { method: 'DELETE' });
                    if (res.success) {
                        toast.success('Price Book deleted successfully');
                        setPriceBooks(prev => prev.filter(b => b.id !== id));
                    }
                } catch (error) {
                    console.error('Error deleting price book', error);
                    toast.error('Error deleting Price Book');
                }
            }
        });
    };

    const filteredBooks = priceBooks.filter(book => 
        book.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        book.code.toLowerCase().includes(searchQuery.toLowerCase()) ||
        book.type.toLowerCase().includes(searchQuery.toLowerCase())
    );

    if (loading) {
        return (
            <div className="flex items-center justify-center min-h-[400px]">
                <Loader2 className="w-8 h-8 animate-spin text-brand-600" />
            </div>
        );
    }

    return (
        <div className="space-y-8 animate-in fade-in duration-500">
            {/* Header section */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-1 flex items-center gap-2">
                        <Scale className="w-5 h-5 text-brand-600" />
                        Price Books Management
                    </h3>
                    <p className="text-slate-500 dark:text-slate-400 text-sm">
                        Create and manage localized price catalogues, currency rules, and promotional pricing structures.
                    </p>
                </div>

                <button
                    onClick={openCreateModal}
                    className="flex items-center justify-center gap-2 px-5 py-2.5 bg-brand-600 hover:bg-brand-700 text-white rounded-xl text-sm font-bold transition-all shadow-lg shadow-brand-500/20 self-start md:self-center"
                >
                    <Plus className="w-4 h-4" />
                    New Price Book
                </button>
            </div>

            {/* Filter / Search Bar */}
            <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-4 shadow-sm">
                <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Search price books by name, code or type..."
                    className="w-full px-4 py-2.5 bg-slate-50 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-brand-500 outline-none transition-all text-sm"
                />
            </div>

            {/* Price Books Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {filteredBooks.map((book) => (
                    <motion.div
                        key={book.id}
                        layout
                        className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-6 shadow-sm hover:shadow-md transition-all group relative flex flex-col justify-between"
                    >
                        <div>
                            <div className="flex justify-between items-start mb-4">
                                <div className="p-3 bg-brand-50 dark:bg-brand-900/20 rounded-2xl">
                                    <BadgeDollarSign className="w-6 h-6 text-brand-600" />
                                </div>
                                <div className="flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                    <button 
                                        onClick={() => openEditModal(book)} 
                                        className="p-2 text-slate-400 hover:text-brand-600 transition-colors"
                                        title="Edit Price Book"
                                    >
                                        <Edit2 className="w-4 h-4" />
                                    </button>
                                    <button 
                                        onClick={() => handleDelete(book.id)} 
                                        className="p-2 text-slate-400 hover:text-rose-600 transition-colors"
                                        title="Delete Price Book"
                                    >
                                        <Trash2 className="w-4 h-4" />
                                    </button>
                                </div>
                            </div>

                            <h5 className="text-lg font-bold text-slate-900 dark:text-white mb-1">{book.name}</h5>
                            <div className="flex flex-wrap items-center gap-2 mb-4">
                                <span className="text-xs font-mono text-slate-400 font-bold">{book.code}</span>
                                <span className="px-2 py-0.5 bg-brand-50 dark:bg-brand-950/30 text-brand-600 rounded text-[10px] font-black uppercase tracking-wider">
                                    {book.type}
                                </span>
                                <span className="px-2 py-0.5 bg-slate-100 dark:bg-slate-800 text-slate-500 rounded text-[10px] font-black uppercase tracking-wider">
                                    {book.currency}
                                </span>
                            </div>

                            <div className="space-y-2.5 text-xs text-slate-500 dark:text-slate-400 border-t border-slate-50 dark:border-slate-800/50 pt-4">
                                <div className="flex items-center gap-2">
                                    <Clock className="w-4 h-4 text-slate-400" />
                                    <span>
                                        {book.validFrom ? (
                                            <>Valid: {new Date(book.validFrom).toLocaleDateString()} &rarr; {book.validTo ? new Date(book.validTo).toLocaleDateString() : 'Forever'}</>
                                        ) : (
                                            'Always Applicable'
                                        )}
                                    </span>
                                </div>
                                <div className="flex items-center gap-2">
                                    <Check className={`w-4 h-4 ${book.isActive ? 'text-emerald-500' : 'text-slate-400'}`} />
                                    <span className="font-bold">
                                        {book.isActive ? (
                                            <span className="text-emerald-600 dark:text-emerald-400">Active / Receiving Overrides</span>
                                        ) : (
                                            <span className="text-slate-400">Disabled / Offline</span>
                                        )}
                                    </span>
                                </div>
                            </div>

                            {/* CUSTOMER_SPECIFIC hint badge */}
                            {book.type === 'CUSTOMER_SPECIFIC' && (
                                <div className="mt-3 flex items-start gap-1.5 px-3 py-2 bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-xl">
                                    <Info className="w-3.5 h-3.5 text-amber-500 mt-0.5 shrink-0" />
                                    <p className="text-[10px] text-amber-700 dark:text-amber-400 leading-tight">
                                        Apply manually: pass <code className="font-mono bg-amber-100 dark:bg-amber-900/40 px-0.5 rounded">{book.code}</code> as <code className="font-mono bg-amber-100 dark:bg-amber-900/40 px-0.5 rounded">priceBookCode</code> when creating an order.
                                    </p>
                                </div>
                            )}
                        </div>
                    </motion.div>
                ))}

                {filteredBooks.length === 0 && (
                    <div className="col-span-full py-16 bg-white dark:bg-slate-900 border border-dashed border-slate-200 dark:border-slate-800 rounded-3xl text-center text-slate-400 flex flex-col items-center justify-center gap-2">
                        <ShieldAlert className="w-10 h-10 text-slate-300 dark:text-slate-600" />
                        <span>No price books found. Create one to begin customizing your catalog pricing.</span>
                    </div>
                )}
            </div>

            {/* Price Book Form Modal */}
            <AnimatePresence>
                {isModalOpen && (
                    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
                        <motion.div
                            initial={{ scale: 0.95, opacity: 0 }}
                            animate={{ scale: 1, opacity: 1 }}
                            exit={{ scale: 0.95, opacity: 0 }}
                            className="bg-white dark:bg-slate-900 rounded-[2.5rem] p-8 w-full max-w-md shadow-2xl border border-slate-100 dark:border-slate-800"
                        >
                            <h4 className="text-2xl font-bold text-slate-900 dark:text-white mb-6">
                                {editingBook ? 'Edit Price Book' : 'New Price Book'}
                            </h4>
                            
                            <form onSubmit={handleSubmit} className="space-y-4">
                                <div>
                                    <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-1.5">Name</label>
                                    <input
                                        type="text"
                                        required
                                        value={formData.name}
                                        onChange={(e) => {
                                            const name = e.target.value;
                                            setFormData(prev => ({
                                                ...prev,
                                                name,
                                                // Auto-update code only while auto-gen is active and not editing
                                                code: (!editingBook && codeAutoGenerated) ? generateCode(name) : prev.code,
                                            }));
                                        }}
                                        className="w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-brand-500 transition-all text-sm"
                                        placeholder="e.g. Eid Campaign Price Book"
                                    />
                                </div>

                                <div>
                                    <div className="flex items-center justify-between mb-1.5">
                                        <label className="text-sm font-bold text-slate-700 dark:text-slate-300">Code / Identifier</label>
                                        {!editingBook && (
                                            <span className={`text-[10px] font-black px-2 py-0.5 rounded-full uppercase tracking-wide ${
                                                codeAutoGenerated
                                                    ? 'bg-brand-100 dark:bg-brand-900/30 text-brand-600 dark:text-brand-400'
                                                    : 'bg-slate-100 dark:bg-slate-800 text-slate-500'
                                            }`}>
                                                {codeAutoGenerated ? '⚡ Auto' : '✎ Manual'}
                                            </span>
                                        )}
                                    </div>
                                    <input
                                        type="text"
                                        required
                                        value={formData.code}
                                        onChange={(e) => {
                                            if (!editingBook) {
                                                setCodeAutoGenerated(false); // user manually typed → stop auto-gen
                                                setFormData({ ...formData, code: e.target.value.toUpperCase() });
                                            }
                                        }}
                                        className={`w-full px-4 py-3 rounded-2xl focus:ring-2 focus:ring-brand-500 transition-all text-sm font-mono ${
                                            editingBook
                                                ? 'bg-slate-100 dark:bg-slate-800/60 text-slate-400 cursor-not-allowed border-none'
                                                : codeAutoGenerated
                                                    ? 'bg-brand-50 dark:bg-brand-950/20 border border-brand-200 dark:border-brand-800 text-brand-700 dark:text-brand-300'
                                                    : 'bg-slate-50 dark:bg-slate-800 border-none text-slate-900 dark:text-white'
                                        }`}
                                        placeholder="AUTO-GENERATED"
                                        readOnly={!!editingBook}
                                    />
                                    {!editingBook && codeAutoGenerated && (
                                        <p className="mt-1 text-[10px] text-slate-400">Auto-generated from name. Click to override.</p>
                                    )}
                                    {editingBook && (
                                        <p className="mt-1 text-[10px] text-slate-400">Code cannot be changed after creation.</p>
                                    )}
                                </div>

                                <div className="grid grid-cols-2 gap-4">
                                    <div>
                                        <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-1.5">Type</label>
                                        <select
                                            value={formData.type}
                                            onChange={(e) => setFormData({ ...formData, type: e.target.value })}
                                            className="w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-brand-500 transition-all text-sm outline-none"
                                        >
                                            <option value="RETAIL">Retail</option>
                                            <option value="WHOLESALE">Wholesale</option>
                                            <option value="PROMOTIONAL">Promotional</option>
                                            <option value="CUSTOMER_SPECIFIC">Customer Specific</option>
                                        </select>
                                    </div>
                                    <div>
                                        <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-1.5">Currency</label>
                                        <select
                                            value={formData.currency}
                                            onChange={(e) => setFormData({ ...formData, currency: e.target.value })}
                                            className="w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-brand-500 transition-all text-sm outline-none"
                                        >
                                            {settings?.supportedCurrencies?.map((c: any) => (
                                                <option key={c.code} value={c.code}>
                                                    {c.code} - {c.name} {c.code === globalCurrency ? '(Primary)' : ''}
                                                </option>
                                            ))}
                                            {(!settings?.supportedCurrencies || settings.supportedCurrencies.length === 0) && (
                                                <option value={globalCurrency}>{globalCurrency} (Primary)</option>
                                            )}
                                        </select>
                                    </div>
                                </div>

                                {/* Type specific notice banner */}
                                {getTypeHelperText() && (
                                    <div className={`p-3.5 border rounded-2xl flex gap-2 items-start text-[11px] leading-relaxed transition-all duration-300 ${getTypeHelperText()?.color}`}>
                                        <Info className="w-4 h-4 shrink-0 mt-0.5" />
                                        <span>{getTypeHelperText()?.text}</span>
                                    </div>
                                )}

                                <div>
                                    <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-1.5">
                                        Valid From {formData.type === 'PROMOTIONAL' && <span className="text-rose-500">*</span>}
                                    </label>
                                    <input
                                        type="datetime-local"
                                        required={formData.type === 'PROMOTIONAL'}
                                        value={formData.validFrom}
                                        onChange={(e) => setFormData({ ...formData, validFrom: e.target.value })}
                                        className="w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-brand-500 transition-all text-sm outline-none"
                                    />
                                </div>

                                <div>
                                    <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-1.5">
                                        Valid To {formData.type === 'PROMOTIONAL' && <span className="text-rose-500">*</span>}
                                    </label>
                                    <input
                                        type="datetime-local"
                                        required={formData.type === 'PROMOTIONAL'}
                                        value={formData.validTo}
                                        onChange={(e) => setFormData({ ...formData, validTo: e.target.value })}
                                        className="w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-brand-500 transition-all text-sm outline-none"
                                    />
                                </div>

                                <div className="flex items-center gap-2 pt-2">
                                    <input
                                        type="checkbox"
                                        id="isActive"
                                        checked={formData.isActive}
                                        onChange={(e) => setFormData({ ...formData, isActive: e.target.checked })}
                                        className="rounded border-slate-300 text-brand-600 focus:ring-brand-500 cursor-pointer"
                                    />
                                    <label htmlFor="isActive" className="text-sm text-slate-700 dark:text-slate-300 font-bold cursor-pointer">Active</label>
                                </div>

                                <div className="flex gap-4 mt-8">
                                    <button
                                        type="button"
                                        onClick={() => setIsModalOpen(false)}
                                        className="flex-1 px-6 py-4 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 font-bold rounded-2xl hover:bg-slate-200 transition-all text-sm"
                                    >
                                        Cancel
                                    </button>
                                    <button
                                        type="submit"
                                        className="flex-1 px-6 py-4 bg-brand-600 text-white font-bold rounded-2xl hover:bg-brand-700 shadow-lg shadow-brand-500/30 transition-all text-sm"
                                    >
                                        {editingBook ? 'Update' : 'Create'}
                                    </button>
                                </div>
                            </form>
                        </motion.div>
                    </div>
                )}
            </AnimatePresence>

            <ConfirmModal
                isOpen={confirmModal.isOpen}
                onClose={() => setConfirmModal({ ...confirmModal, isOpen: false })}
                onConfirm={confirmModal.onConfirm}
                title={confirmModal.title}
                message={confirmModal.message}
                isDangerous={true}
            />
        </div>
    );
}
