'use client';

import React, { useMemo, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
    Scale, 
    Plus, 
    Trash2, 
    Edit2, 
    Loader2, 
    BadgeDollarSign, 
    Check, 
    ShieldAlert, 
    Clock,
    Info,
    Sparkles,
} from 'lucide-react';
import ConfirmModal from '@/components/shared/ConfirmModal';
import { usePriceBookDashboard } from '../hooks/usePriceBookDashboard';
import { generateCode, getTypeHelperText } from '../utils/priceBookHelpers';
import PriceBookRationaleModal from './PriceBookRationaleModal';
import type { PriceBook } from '../types';

export default function PriceBooks() {
    const [aiBook, setAiBook] = useState<PriceBook | null>(null);
    const {
        priceBooks,
        loading,
        isModalOpen,
        setIsModalOpen,
        editingBook,
        searchQuery,
        setSearchQuery,
        codeAutoGenerated,
        setCodeAutoGenerated,
        confirmModal,
        setConfirmModal,
        formData,
        setFormData,
        openCreateModal,
        openEditModal,
        handleSubmit,
        handleDelete,
        globalCurrency,
        settings,
    } = usePriceBookDashboard();

    const filteredBooks = useMemo(() => {
        const query = searchQuery.trim().toLowerCase();
        if (!query) return priceBooks;
        return priceBooks.filter(book => 
            book.name.toLowerCase().includes(query) ||
            book.code.toLowerCase().includes(query) ||
            book.type.toLowerCase().includes(query)
        );
    }, [priceBooks, searchQuery]);

    if (loading) {
        return (
            <div className="flex items-center justify-center min-h-[400px]">
                <Loader2 className="w-8 h-8 animate-spin text-brand-600" />
            </div>
        );
    }

    return (
        <div className="space-y-8 animate-in fade-in duration-500">
            {/* Header section */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-1 flex items-center gap-2">
                        <Scale className="w-5 h-5 text-brand-600" />
                        Price Books Management
                    </h3>
                    <p className="text-slate-500 dark:text-slate-400 text-sm">
                        Create and manage localized price catalogues, currency rules, and promotional pricing structures.
                    </p>
                </div>

                <button
                    onClick={openCreateModal}
                    className="flex items-center justify-center gap-2 px-5 py-2.5 bg-brand-600 hover:bg-brand-700 text-white rounded-xl text-sm font-bold transition-all shadow-lg shadow-brand-500/20 self-start md:self-center"
                >
                    <Plus className="w-4 h-4" />
                    New Price Book
                </button>
            </div>

            {/* Filter / Search Bar */}
            <div className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-4 shadow-sm">
                <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Search price books by name, code or type..."
                    className="w-full px-4 py-2.5 bg-slate-50 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-brand-500 outline-none transition-all text-sm"
                />
            </div>

            {/* Price Books Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {filteredBooks.map((book) => (
                    <motion.div
                        key={book.id}
                        layout
                        className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-6 shadow-sm hover:shadow-md transition-all group relative flex flex-col justify-between"
                    >
                        <div>
                            <div className="flex justify-between items-start mb-4">
                                <div className="p-3 bg-brand-50 dark:bg-brand-900/20 rounded-2xl">
                                    <BadgeDollarSign className="w-6 h-6 text-brand-600" />
                                </div>
                                <div className="flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                                    <button
                                        type="button"
                                        onClick={() => setAiBook(book)}
                                        className="p-2 text-violet-500 hover:text-violet-700 transition-colors"
                                        title="AI pricing rationale"
                                    >
                                        <Sparkles className="w-4 h-4" />
                                    </button>
                                    <button 
                                        onClick={() => openEditModal(book)} 
                                        className="p-2 text-slate-400 hover:text-brand-600 transition-colors"
                                        title="Edit Price Book"
                                    >
                                        <Edit2 className="w-4 h-4" />
                                    </button>
                                    <button 
                                        onClick={() => handleDelete(book.id)} 
                                        className="p-2 text-slate-400 hover:text-rose-600 transition-colors"
                                        title="Delete Price Book"
                                    >
                                        <Trash2 className="w-4 h-4" />
                                    </button>
                                </div>
                            </div>

                            <h5 className="text-lg font-bold text-slate-900 dark:text-white mb-1">{book.name}</h5>
                            <div className="flex flex-wrap items-center gap-2 mb-4">
                                <span className="text-xs font-mono text-slate-400 font-bold">{book.code}</span>
                                <span className="px-2 py-0.5 bg-brand-50 dark:bg-brand-950/30 text-brand-600 rounded text-[10px] font-black uppercase tracking-wider">
                                    {book.type}
                                </span>
                                <span className="px-2 py-0.5 bg-slate-100 dark:bg-slate-800 text-slate-500 rounded text-[10px] font-black uppercase tracking-wider">
                                    {book.currency}
                                </span>
                            </div>

                            <div className="space-y-2.5 text-xs text-slate-500 dark:text-slate-400 border-t border-slate-50 dark:border-slate-800/50 pt-4">
                                <div className="flex items-center gap-2">
                                    <Clock className="w-4 h-4 text-slate-400" />
                                    <span>
                                        {book.validFrom ? (
                                            <>Valid: {new Date(book.validFrom).toLocaleDateString()} &rarr; {book.validTo ? new Date(book.validTo).toLocaleDateString() : 'Forever'}</>
                                        ) : (
                                            'Always Applicable'
                                        )}
                                    </span>
                                </div>
                                <div className="flex items-center gap-2">
                                    <Check className={`w-4 h-4 ${book.isActive ? 'text-emerald-500' : 'text-slate-400'}`} />
                                    <span className="font-bold">
                                        {book.isActive ? (
                                            <span className="text-emerald-600 dark:text-emerald-400">Active / Receiving Overrides</span>
                                        ) : (
                                            <span className="text-slate-400">Disabled / Offline</span>
                                        )}
                                    </span>
                                </div>
                            </div>

                            {/* CUSTOMER_SPECIFIC hint badge */}
                            {book.type === 'CUSTOMER_SPECIFIC' && (
                                <div className="mt-3 flex items-start gap-1.5 px-3 py-2 bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-xl">
                                    <Info className="w-3.5 h-3.5 text-amber-500 mt-0.5 shrink-0" />
                                    <p className="text-[10px] text-amber-700 dark:text-amber-400 leading-tight">
                                        Apply manually: pass <code className="font-mono bg-amber-100 dark:bg-amber-900/40 px-0.5 rounded">{book.code}</code> as <code className="font-mono bg-amber-100 dark:bg-amber-900/40 px-0.5 rounded">priceBookCode</code> when creating an order.
                                    </p>
                                </div>
                            )}
                        </div>
                    </motion.div>
                ))}

                {filteredBooks.length === 0 && (
                    <div className="col-span-full py-16 bg-white dark:bg-slate-900 border border-dashed border-slate-200 dark:border-slate-800 rounded-3xl text-center text-slate-400 flex flex-col items-center justify-center gap-2">
                        <ShieldAlert className="w-10 h-10 text-slate-300 dark:text-slate-600" />
                        <span>No price books found. Create one to begin customizing your catalog pricing.</span>
                    </div>
                )}
            </div>

            {/* Price Book Form Modal */}
            <AnimatePresence>
                {isModalOpen && (
                    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
                        <motion.div
                            initial={{ scale: 0.95, opacity: 0 }}
                            animate={{ scale: 1, opacity: 1 }}
                            exit={{ scale: 0.95, opacity: 0 }}
                            className="bg-white dark:bg-slate-900 rounded-[2.5rem] p-8 w-full max-w-md shadow-2xl border border-slate-100 dark:border-slate-800"
                        >
                            <h4 className="text-2xl font-bold text-slate-900 dark:text-white mb-6">
                                {editingBook ? 'Edit Price Book' : 'New Price Book'}
                            </h4>
                            
                            <form onSubmit={handleSubmit} className="space-y-4">
                                <div>
                                    <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-1.5">Name</label>
                                    <input
                                        type="text"
                                        required
                                        value={formData.name}
                                        onChange={(e) => {
                                            const name = e.target.value;
                                            setFormData(prev => ({
                                                ...prev,
                                                name,
                                                // Auto-update code only while auto-gen is active and not editing
                                                code: (!editingBook && codeAutoGenerated) ? generateCode(name) : prev.code,
                                            }));
                                        }}
                                        className="w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-brand-500 transition-all text-sm"
                                        placeholder="e.g. Eid Campaign Price Book"
                                    />
                                </div>

                                <div>
                                    <div className="flex items-center justify-between mb-1.5">
                                        <label className="text-sm font-bold text-slate-700 dark:text-slate-300">Code / Identifier</label>
                                        {!editingBook && (
                                            <span className={`text-[10px] font-black px-2 py-0.5 rounded-full uppercase tracking-wide ${
                                                codeAutoGenerated
                                                    ? 'bg-brand-100 dark:bg-brand-900/30 text-brand-600 dark:text-brand-400'
                                                    : 'bg-slate-100 dark:bg-slate-800 text-slate-500'
                                            }`}>
                                                {codeAutoGenerated ? '⚡ Auto' : '✎ Manual'}
                                            </span>
                                        )}
                                    </div>
                                    <input
                                        type="text"
                                        required
                                        value={formData.code}
                                        onChange={(e) => {
                                            if (!editingBook) {
                                                setCodeAutoGenerated(false); // user manually typed → stop auto-gen
                                                setFormData(prev => ({ ...prev, code: e.target.value.toUpperCase() }));
                                            }
                                        }}
                                        className={`w-full px-4 py-3 rounded-2xl focus:ring-2 focus:ring-brand-500 transition-all text-sm font-mono ${
                                            editingBook
                                                ? 'bg-slate-100 dark:bg-slate-800/60 text-slate-400 cursor-not-allowed border-none'
                                                : codeAutoGenerated
                                                    ? 'bg-brand-50 dark:bg-brand-950/20 border border-brand-200 dark:border-brand-800 text-brand-700 dark:text-brand-300'
                                                    : 'bg-slate-50 dark:bg-slate-800 border-none text-slate-900 dark:text-white'
                                        }`}
                                        placeholder="AUTO-GENERATED"
                                        readOnly={!!editingBook}
                                    />
                                    {!editingBook && codeAutoGenerated && (
                                        <p className="mt-1 text-[10px] text-slate-400">Auto-generated from name. Click to override.</p>
                                    )}
                                    {editingBook && (
                                        <p className="mt-1 text-[10px] text-slate-400">Code cannot be changed after creation.</p>
                                    )}
                                </div>

                                <div className="grid grid-cols-2 gap-4">
                                    <div>
                                        <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-1.5">Type</label>
                                        <select
                                            value={formData.type}
                                            onChange={(e) => setFormData(prev => ({ ...prev, type: e.target.value }))}
                                            className="w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-brand-500 transition-all text-sm outline-none"
                                        >
                                            <option value="RETAIL">Retail</option>
                                            <option value="WHOLESALE">Wholesale</option>
                                            <option value="PROMOTIONAL">Promotional</option>
                                            <option value="CUSTOMER_SPECIFIC">Customer Specific</option>
                                        </select>
                                    </div>
                                    <div>
                                        <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-1.5">Currency</label>
                                        <select
                                            value={formData.currency}
                                            onChange={(e) => setFormData(prev => ({ ...prev, currency: e.target.value }))}
                                            className="w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-brand-500 transition-all text-sm outline-none"
                                        >
                                            {settings?.supportedCurrencies?.map((c: any) => (
                                                <option key={c.code} value={c.code}>
                                                    {c.code} - {c.name} {c.code === globalCurrency ? '(Primary)' : ''}
                                                </option>
                                            ))}
                                            {(!settings?.supportedCurrencies || settings.supportedCurrencies.length === 0) && (
                                                <option value={globalCurrency}>{globalCurrency} (Primary)</option>
                                            )}
                                        </select>
                                    </div>
                                </div>

                                {/* Type specific notice banner */}
                                {getTypeHelperText(formData.type) && (
                                    <div className={`p-3.5 border rounded-2xl flex gap-2 items-start text-[11px] leading-relaxed transition-all duration-300 ${getTypeHelperText(formData.type)?.color}`}>
                                        <Info className="w-4 h-4 shrink-0 mt-0.5" />
                                        <span>{getTypeHelperText(formData.type)?.text}</span>
                                    </div>
                                )}

                                <div>
                                    <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-1.5">
                                        Valid From {formData.type === 'PROMOTIONAL' && <span className="text-rose-500">*</span>}
                                    </label>
                                    <input
                                        type="datetime-local"
                                        required={formData.type === 'PROMOTIONAL'}
                                        value={formData.validFrom}
                                        onChange={(e) => setFormData(prev => ({ ...prev, validFrom: e.target.value }))}
                                        className="w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-brand-500 transition-all text-sm outline-none"
                                    />
                                </div>

                                <div>
                                    <label className="block text-sm font-bold text-slate-700 dark:text-slate-300 mb-1.5">
                                        Valid To {formData.type === 'PROMOTIONAL' && <span className="text-rose-500">*</span>}
                                    </label>
                                    <input
                                        type="datetime-local"
                                        required={formData.type === 'PROMOTIONAL'}
                                        value={formData.validTo}
                                        onChange={(e) => setFormData(prev => ({ ...prev, validTo: e.target.value }))}
                                        className="w-full px-4 py-3 bg-slate-50 dark:bg-slate-800 border-none rounded-2xl focus:ring-2 focus:ring-brand-500 transition-all text-sm outline-none"
                                    />
                                </div>

                                <div className="flex items-center gap-2 pt-2">
                                    <input
                                        type="checkbox"
                                        id="isActive"
                                        checked={formData.isActive}
                                        onChange={(e) => setFormData(prev => ({ ...prev, isActive: e.target.checked }))}
                                        className="rounded border-slate-300 text-brand-600 focus:ring-brand-500 cursor-pointer"
                                    />
                                    <label htmlFor="isActive" className="text-sm text-slate-700 dark:text-slate-300 font-bold cursor-pointer">Active</label>
                                </div>

                                <div className="flex gap-4 mt-8">
                                    <button
                                        type="button"
                                        onClick={() => setIsModalOpen(false)}
                                        className="flex-1 px-6 py-4 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 font-bold rounded-2xl hover:bg-slate-200 transition-all text-sm"
                                    >
                                        Cancel
                                    </button>
                                    <button
                                        type="submit"
                                        className="flex-1 px-6 py-4 bg-brand-600 text-white font-bold rounded-2xl hover:bg-brand-700 shadow-lg shadow-brand-500/30 transition-all text-sm"
                                    >
                                        {editingBook ? 'Update' : 'Create'}
                                    </button>
                                </div>
                            </form>
                        </motion.div>
                    </div>
                )}
            </AnimatePresence>

            <ConfirmModal
                isOpen={confirmModal.isOpen}
                onClose={() => setConfirmModal(prev => ({ ...prev, isOpen: false }))}
                onConfirm={confirmModal.onConfirm}
                title={confirmModal.title}
                message={confirmModal.message}
                isDangerous={true}
            />

            {aiBook && (
                <PriceBookRationaleModal
                    book={aiBook}
                    allBooks={priceBooks}
                    onClose={() => setAiBook(null)}
                />
            )}
        </div>
    );
}
