export interface DefaultRoleDefinition {
  name: string
  description: string
  permCodes: string[]
}

export const DEFAULT_ROLE_DEFINITIONS: DefaultRoleDefinition[] = [
  {
    name: 'Branch Manager',
    description: 'Full operational control across the tenant.',
    permCodes: [
      'pos:create-sale',
      'pos:manage-shifts',
      'pos:override-price',
      'pos:apply-discount',
      'pos:void-transaction',
      'pos:refund-sale',
      'pos:manage-cash-drawer',
      'pos:view-reports',
      'catalog:read',
      'catalog:write',
      'catalog:publish',
      'catalog:featured',
      'inventory:read',
      'inventory:write',
      'inventory:adjust',
      'inventory:transfer',
      'inventory:cycle-count',
      'inventory:report',
      'purchasing:read',
      'purchasing:write',
      'purchasing:approve',
      'purchasing:receive-grn',
      'supplier:manage',
      'supplier:view-pricing',
      'orders:read',
      'orders:write',
      'orders:cancel',
      'orders:approve',
      'orders:export',
      'returns:read',
      'returns:write',
      'returns:approve',
      'hrm:clock-attendance',
      'hrm:view-attendance-report',
      'hrm:manage-employees',
      'hrm:approve-leave',
      'hrm:manage-documents',
      'finance:read-ledger',
      'finance:write-expense',
      'accounting:read',
      'accounting:write',
      'invoices:manage',
      'reports:read',
      'reports:export',
      'reports:schedule',
      'users:read',
      'users:invite',
      'crm:read',
      'crm:write',
      'crm:segment',
      'fulfillment:manage',
      'settings:manage',
      'ai:use',
    ],
  },
  {
    name: 'Accountant',
    description: 'Financial, general ledger, and reconciliation control.',
    permCodes: [
      'finance:read-ledger',
      'finance:write-expense',
      'finance:post-journal',
      'finance:reverse-journal',
      'finance:close-period',
      'finance:manage-budget',
      'accounting:read',
      'accounting:write',
      'accounting:manage-coa',
      'invoices:manage',
      'invoices:approve',
      'payments:read',
      'payments:write',
      'payments:reconcile',
      'reports:read',
      'reports:view-financial',
      'reports:export',
      'purchasing:read',
      'supplier:view-pricing',
    ],
  },
  {
    name: 'Sales Associate',
    description: 'Standard retail sales and checkout operator.',
    permCodes: [
      'pos:create-sale',
      'inventory:read',
      'orders:read',
      'orders:write',
      'returns:read',
      'catalog:read',
      'crm:read',
      'payments:read',
      'hrm:clock-attendance',
    ],
  },
  {
    name: 'HR Manager',
    description: 'Comprehensive human resources, employee file, and payroll management.',
    permCodes: [
      'hrm:clock-attendance',
      'hrm:correct-attendance',
      'hrm:view-attendance-report',
      'hrm:process-payroll',
      'hrm:approve-payroll',
      'hrm:view-payslip',
      'hrm:manage-employees',
      'hrm:delete-employee',
      'hrm:approve-leave',
      'hrm:manage-documents',
      'users:read',
      'reports:read',
    ],
  },
  {
    name: 'Procurement Officer',
    description: 'Purchase orders, stock receipts, and supplier contract manager.',
    permCodes: [
      'purchasing:read',
      'purchasing:write',
      'purchasing:approve',
      'purchasing:receive-grn',
      'inventory:read',
      'supplier:manage',
      'supplier:view-pricing',
      'reports:read',
    ],
  },
  {
    name: 'Inventory Manager',
    description: 'Warehouse movement, stock adjustments, and carrier logistics controller.',
    permCodes: [
      'inventory:read',
      'inventory:write',
      'inventory:adjust',
      'inventory:transfer',
      'inventory:cycle-count',
      'inventory:report',
      'catalog:read',
      'reports:read',
      'fulfillment:manage',
      'logistics:manage',
      'shipping:manage',
    ],
  },
  {
    name: 'Viewer',
    description: 'Full read-only auditing and observation access.',
    permCodes: [
      'catalog:read',
      'inventory:read',
      'purchasing:read',
      'orders:read',
      'returns:read',
      'payments:read',
      'finance:read-ledger',
      'accounting:read',
      'crm:read',
      'reports:read',
      'users:read',
    ],
  },
]
