export enum AccountType {
  ASSET = 'ASSET',
  LIABILITY = 'LIABILITY',
  EQUITY = 'EQUITY',
  REVENUE = 'REVENUE',
  EXPENSE = 'EXPENSE',
}

export enum AccountCategory {
  CASH_BANK = 'CASH_BANK',
  RECEIVABLE = 'RECEIVABLE',
  INVENTORY = 'INVENTORY',
  FIXED_ASSET = 'FIXED_ASSET',
  PAYABLE = 'PAYABLE',
  EQUITY = 'EQUITY',
  SALES = 'SALES',
  COGS = 'COGS',
  OPERATING_EXPENSE = 'OPERATING_EXPENSE',
  OTHER = 'OTHER',
}
