export enum ExpenseCategory {
    SHIPPING = 'SHIPPING',
    PACKAGING = 'PACKAGING',
    MARKETING = 'MARKETING',
    SOFTWARE = 'SOFTWARE',
    SALARIES = 'SALARIES',
    UTILITIES = 'UTILITIES',
    MAINTENANCE = 'MAINTENANCE',
    OTHER = 'OTHER'
}
