export enum InventoryTransactionReferenceType {
  ORDER = 'ORDER',
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',
  STOCK_TRANSFER = 'STOCK_TRANSFER',
  INITIAL_IMPORT = 'INITIAL_IMPORT',
  SALES_RETURN = 'SALES_RETURN',
  PURCHASE_RETURN = 'PURCHASE_RETURN',
  MANUAL = 'MANUAL',
  GOODS_RECEIVED_NOTE = 'GOODS_RECEIVED_NOTE',
}
