export enum SupplierCategory {
  RAW_MATERIALS = 'RAW_MATERIALS',
  PACKAGING = 'PACKAGING',
  SERVICES = 'SERVICES',
  EQUIPMENT = 'EQUIPMENT',
  LOGISTICS = 'LOGISTICS',
  IT_SOFTWARE = 'IT_SOFTWARE',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  OTHER = 'OTHER',
}
