export const DEFAULT_SETTINGS = {
  logo: "",
  favicon: "",
  brandName: "LuxeAudio",
  siteDescription:
    "Elevating your audio experience with premium sound and design.",
  metaTitle: "",
  contactEmail: "support@luxesaas.com",
  contactPhone: "+8801722222222",
  whatsappPhone: "+8801722222222",
  address: "123 Audio Street, Sound City, SC 90210",
  currency: "BDT",
  currencySymbol: "৳",
  supportedCurrencies: [
    { code: "BDT", symbol: "৳", rate: 1, name: "Bangladeshi Taka" },
    { code: "USD", symbol: "$", rate: 120, name: "US Dollar" },
  ],
  socialLinks: { facebook: "", twitter: "", instagram: "", linkedin: "" },
  marketing: {
    googleAnalyticsId: "",
    googleSiteVerification: "",
    facebookPixelId: "",
    facebookDomainVerification: "",
    requireConsent: true,
  },
  navbar: {
    layout: "default",
    template: "classic",
    backgroundColor: "",
    textColor: "",
    shadowIntensity: "subtle",
    hoverEffect: "underline",
    borderRadius: "xl",
    sticky: true,
    maxWidth: "standard",
    bottomShape: "none",
    backgroundPattern: "none",
    transparent: false,
    showCurrency: true,
    links: [],
  },
  footer: {
    template: "classic",
    backgroundColor: "",
    textColor: "",
    brandColor: "",
    borderColor: "",
    shadowIntensity: "none",
    borderRadius: "none",
    topShape: "none",
    backgroundPattern: "none",
    glassEffect: false,
    columns: "4",
    showSocialLinks: true,
    showNewsletter: true,
    description: "",
    copyright: "",
    sections: [],
  },
  productsPage: {
    bannerHeadline: "Our Collection",
    bannerSubheadline: "Premium products curated for you.",
    bannerTagline: "Exclusive Collection",
    bannerImage: "",
    bannerBackgroundColor: "",
    bannerOverlayOpacity: 40,
    bannerTextColor: "#000000",
    bannerFullWidth: false,
    bannerShow: true,
    bannerStyle: "modern",
    productsPerRow: 4,
    sidebarStyle: "modern",
    showSearch: true,
    showCategories: true,
    showBrands: true,
    showPriceFilter: true,
  },
  singleProductPage: {
    showBreadcrumb: true,
    showRating: true,
    showStock: true,
    showFeatures: true,
    showShare: true,
    showPromotions: true,
    showStickyCart: true,
    showRelatedProducts: true,
    showProductReviews: true,
    showProductFAQs: true,
    relatedProductsPerRow: 4,
  },
  offersPage: {
    bannerShow: true,
    bannerHeadline: "Special Deals & Offers",
    bannerSubheadline: "Save big on our hottest promotions — grab these deals before they're gone!",
    showFilters: true,
    productsPerRow: 5,
    bannerHeight: 400,
    bannerFullWidth: false,
    bannerImage: "",
    bannerBackgroundColor: "",
    bannerTextColor: "#ffffff",
  },
  robotsTxt: "",
  labelSettings: {
    newArrivalText: "New",
    bestSellerText: "Best Seller",
  },
  timezone: "Asia/Dhaka",
  locale: "en-US",
  theme: {
    mode: "system",
    primaryColor: "#2563eb",
    accentColor: "#0f172a",
    fontFamily: "Inter",
  },
  defaultBranchId: "",
  branding: {
    footerText: "",
    brandMarkUrl: "",
    showPoweredBy: true,
  },
};
